### ISSUE TITLE
Messages are not received.

### ISSUE THREAD

**Issue by Saltoon** [Gamer92000/TeamSpeak-3-Telegram-Bridge#1] opened 2021-06-21 13:57 UTC
It seems that I did everything according to the instructions, but no messages come, what am I doing wrong?
![Telegram Bridge  Config](https://user-images.githubusercontent.com/82321695/122774266-b6a14a00-d2b1-11eb-9599-846485cfe88f.png)

**Comment by Gamer92000** [comment] 2022-12-19 16:32
I am sorry. Somehow I missed this issue altogether.

Seeing that this was now almost two years ago, I presume that the issue is no longer of relevance.
On the off chance that this is still relevant though, I would recommend you make sure, that you send a message to the bot first, so it has the necessary permissions to message you.

I will close this issue for now. If you require further assistance, feel free to open it again.

**Closed as completed by Gamer92000** 2022-12-19 16:32 UTC
